### ISSUE TITLE
切分代码无判断视频流

### ISSUE THREAD

**Issue by du5** [Pearlulu/h5ai_dplayer_hls#3]
https://github.com/Pearlulu/h5ai_dplayer_hls/blob/ead81a39a831b4ed8c7cccef94de2712ebc53856/hls_aria2.sh#L14
https://github.com/Pearlulu/h5ai_dplayer_hls/blob/ead81a39a831b4ed8c7cccef94de2712ebc53856/hls_general.sh#L12

该代码切分此格式无异常

```bash
Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 1788 kb/s, 25 fps, 25 tbr, 90k tbn, 50 tbc (default)
```

大佬有完善的打算吗？

**Comment by du5** [comment]
视频好像只有放在h5ai根目录下才会播放ts其他子目录直接读取了源文件

**Comment by du5** [comment]
> 元旦快乐！

**Comment by Pearlulu** [comment]
这个切片脚本只算一个简单演示，ffmpeg我也没太搞明白，需要自己研究。
子目录读取源文件可能是切片没放对位置。
```
bbb/ccc/aaa.mp4  => bbb/ccc/__aaa.mp4__/video.m3u8
```

**Comment by du5** [comment]
好的 老板。感谢回复
